# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container php app to EC2 Instances 

on:
  push:
    branches:
      - main 
    paths:
      - 'php-web-app/**'
  workflow_dispatch:

env:
  IMAGE_NAME: php_bitcot
  VERSION: latest

jobs:

  build:
    runs-on: 'ubuntu-latest' 

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push container image to registry
        run: |
          docker build . -t  91469/php_bitcot:latest
          docker push 91469/php_bitcot:latest
